### ISSUE TITLE
Unknown guild

### ISSUE THREAD

**Issue by SoundDr0ut** [Syaoran2014/Alice#14]
![image](https://github.com/user-attachments/assets/6e24bc1f-e128-4d60-ad1b-65f67fa33ee0)

**Comment by Syaoran2014** [comment]
@SoundDr0ut  You should delete out data/roleMenuConfig.json, this was a residue test file I was using, it tries to load if it exists on startup. 
I removed it recently so this shouldn't be an issue in newer clones.
